name: Build PS3 PKG

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build in Docker
      run: |
        docker run --rm -v $(pwd):/src -w /src bucanero/ps3dev:latest make pkg

    - name: Upload PKG File
      uses: actions/upload-artifact@v4
      with:
        name: PS3-Game-PKG
        path: "*.pkg"
