name: Build PS3 PKG

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps3dev/ps3dev:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Compile PKG
      run: |
        make pkg

    - name: Upload PKG File
      uses: actions/upload-artifact@v4
      with:
        name: PS3-Game-PKG
        path: "*.pkg"
